### ISSUE TITLE
Wowhead links and tooltips should be loaded from shadowlands data, not ptr.

### ISSUE THREAD

**Issue by MysticalOS** [QartemisT/JournalViewer#2]
IE
https://shadowlands.wowhead.com/spell=309296/severed-consciousness

vs

https://ptr.wowhead.com/spell=309296/severed-consciousness

(yes example is same ono both, it's not even a shadowlands spell, it's just an example)

However they have forked shadowlands into 9.0.2 and will continue adding/changing/updating it while 9.0.1 (ptr and soon prepatch) is data locked now.

**Comment by QartemisT** [comment]
Resolved in dev. Links are now formatted based on the build dropdown.
